-- Auto-generated from schema-map-postgres.yaml (map@4ae85c5)
-- engine: postgres
-- table:  rewrap_jobs

CREATE TABLE IF NOT EXISTS rewrap_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_wrapper_id BIGINT NOT NULL,
  target_kms1_key_id BIGINT NULL,
  target_kms2_key_id BIGINT NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  started_at   TIMESTAMPTZ(6) NULL,
  finished_at  TIMESTAMPTZ(6) NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT NULL,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_rewrap_status CHECK (status IN ('pending','running','done','failed')),
  CONSTRAINT chk_rewrap_attempts CHECK (attempts >= 0)
);
